name: initialize-env
description: Initialize environment
runs:
  using: 'composite'
  steps:
    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@v1.1
      with:
        version: 1.10.0
    - name: Setup Vulkan dependencies
      shell: bash
      run: sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config libwayland-dev
    - name: Cache Vcpkg
      id: cache-vcpkg
      uses: actions/cache@v3
      with:
        path: ~/.cache/vcpkg/archives
        key: ${{ runner.os }}-vcpkg-cache